//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTrans.WebAPI.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<Manufacturer> Manufacturers { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<SchedulesRoute> SchedulesRoutes { get; set; }
        public virtual DbSet<Stop> Stops { get; set; }
        public virtual DbSet<StopsInRoute> StopsInRoutes { get; set; }
        public virtual DbSet<Transport> Transports { get; set; }
        public virtual DbSet<TypesRoute> TypesRoutes { get; set; }
        public virtual DbSet<TypesTransport> TypesTransports { get; set; }
    }
}
