//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTrans.WebAPI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchedulesRoute
    {
        public int ID { get; set; }
        public int RouteID { get; set; }
        public bool IsWeekday { get; set; }
        public System.TimeSpan TimeWork { get; set; }
    
        public virtual Route Route { get; set; }
    }
}
