//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTrans.WebAPI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transport
    {
        public int ID { get; set; }
        public int ModelD { get; set; }
        public int ProductionYear { get; set; }
        public string VIN { get; set; }
        public string RegistrationMark { get; set; }
        public int CityID { get; set; }
        public Nullable<int> DriverID { get; set; }
        public Nullable<int> RouteID { get; set; }
    
        public virtual City City { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Model Model { get; set; }
        public virtual Route Route { get; set; }
    }
}
